content:
  - name: blocks
    label: SABURO™ | Корисне
    type: collection
    path: _blocks
    format: yaml-frontmatter
    fields:
      - name: title
        label: Назва
        type: string
        required: true
      - name: slug
        label: Посилання
        type: string
        required: true
      - name: order
        label: Порядок
        type: number
        required: false
      - name: hidden
        label: Прихований
        type: boolean
        required: false
        default: false
      - name: image
        label: Зображення
        type: string
        required: true
      - name: gif_image
        label: GIF
        type: string
        required: false
      - name: back_url
        label: URL кнопки "Назад"
        type: string
        required: false
      - name: back_label
        label: Назва кнопки "Назад"
        type: string
        required: false
      - name: categories
        label: Категорії
        type: select
        required: true
        options:
          multiple: true
          values:
            - label: StreamElements
              value: StreamElements
            - label: Streamer.bot
              value: Streamer.bot
            - label: Twitch
              value: Twitch
            - label: OBS
              value: OBS
      - name: tabs
        label: Вкладки
        type: object
        list: true
        required: false
        fields:
          - name: id
            label: ID вкладки
            type: string
            required: true
            hint: "наприклад, buttons"
          - name: icon
            label: Іконка Material Ico
            type: string
            required: false
            hint: "наприклад, format_align_left"
          - name: svg_icon
            label: SVG-іконка (URL)
            type: string
            required: false
            hint: "наприклад, /svg/obs.svg"
          - name: label
            label: Назва вкладки
            type: string
            required: true
            hint: "наприклад, Кнопки"
      - name: embed_max_width
        label: Макс. ширина вбудованих медіа
        type: string
        required: false
        hint: "Наприклад, 600px або 80%"
      - name: body
        label: Вміст
        type: markdown
        required: false