content:
  - name: blocks
    label: SABURO™ | Корисне
    type: collection
    path: _blocks
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: order
        label: Sort Order
        type: number
        required: false
      - name: image
        label: Static Image URL
        type: string
        required: true
      - name: gif_image
        label: GIF Image URL (optional)
        type: string
        required: false
      - name: back_url
        label: Back Button URL (optional)
        type: string
        required: false
      - name: back_label
        label: Back Button Label (optional)
        type: string
        required: false
      - name: categories
        label: Categories
        type: select
        required: true
        options:
          multiple: true
          values:
            - label: StreamElements
              value: StreamElements
            - label: Streamer.bot
              value: Streamer.bot
            - label: Twitch
              value: Twitch
            - label: OBS
              value: OBS
      - name: description
        label: Short Description
        type: text
        required: false
      - name: body
        label: Full Info Content
        type: markdown
        required: false